[package]
name = "tokio-socket-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib"]

[dependencies]
dashmap = "5.4.0"
futures = { version = "0.3.28", default-features = false, features = ["async-await"] }
libc = "0.2.146"
socket2 = "0.5.3"
tokio = { version = "1.28.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
