name: PR Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        shared: ["ON", "OFF"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install LLVM and Clang
        run: |
          brew update || true
          brew install llvm@17 || true

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: |
          eval "$(brew shellenv)"
          cmake -B ${{github.workspace}}/build \
                -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
                -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
                -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
                -DBUILD_SHARED_LIBS=${{ matrix.shared }}

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --parallel 4 --config ${{env.BUILD_TYPE}} --verbose

      - name: Test
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

      - name: Install
        run: sudo cmake --install build --config Release

      - name: Test Linking
        working-directory: ${{github.workspace}}/tests/test_find_package
        run: |
          eval "$(brew shellenv)"
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          ./build/helloworld_server &
          SERVER_PID=$!
          # Give the server time to start
          sleep 1
          rsp=$(curl http://127.0.0.1:49999)
          kill $SERVER_PID
          if [[ "$rsp" == "Hello, world" ]]; then
            echo "Test passed"
            exit 0
          else
            echo "Test failed"
            exit 1
          fi

      - name: Test Build Examples
        working-directory: ${{github.workspace}}/examples/echo_server
        run: |
          eval "$(brew shellenv)"
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
