name: Push Dev Container

on:
  workflow_dispatch:
  push:
    paths:
      - dockerfile/**
    branches: [ "main" ]
  pull_request:
    paths:
      - dockerfile/**
    branches: [ "main" ]

jobs:
  build-dev-containers:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ["focal", "jammy", "debian-10", "debian-11"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile/dev-containers/${{ matrix.os }}/Dockerfile
          push: true
          tags: congyuwang/socket-manager-dev:${{ matrix.os }}
          cache-from: type=registry,ref=congyuwang/socket-manager-dev:${{ matrix.os }}
          cache-to: type=inline
